### PR TITLE
LPS-102119 Adds clay utilities to clay and admin

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by jbalsas** [comment]
ci:test:sf

**Comment by jbalsas** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
Pull request submitted to https://github.com/marcoscv-work/liferay-portal/pull/268. [See changes here.](https://github.com/eduardoallegrini/liferay-portal/compare/3c15c21b35ce~1...3c15c21b35ce)

**Pull request closed without merging**
