### PR TITLE
LPS-114086 - Apply the use of ClayLayout component in sharing-web

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
ci:test:sf

**Comment by marcoscv-work** [comment]
ci:test:stable

**Comment by marcoscv-work** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
ci:test:stop

**Comment by eduardoallegrini** [comment]
Pull request submitted to jbalsas#2215.

**Pull request closed without merging**
