### PR TITLE
LPS-96291 | Horizontal scrolling in a permissions popup

### PR DESCRIPTION
**Pull request by markocikos**
Hey @eduardoallegrini ,

This is the followup on https://github.com/eduardoallegrini/liferay-portal/pull/23, with added requested changes.

I intentionally put in `media-breakpoint-up(sm)` instead of `media-breakpoint-up(md)`, 576px looks to me like a more fitting breakpoint.

Please review the changes.

Thank you!

/cc @jbalsas

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
Pull request submitted to https://github.com/marcoscv-work/liferay-portal/pull/264.

**Comment by eduardoallegrini** [comment]
Hey @markocikos `@include media-breakpoint-down(sm)` for Bootstrap is `@media (max-width: 767.98px) { ... }` that's why I suggested to change it into `@include media-breakpoint-up(md)` that is `@media (min-width: 768px) { ... }` https://getbootstrap.com/docs/4.3/layout/overview/#responsive-breakpoint

**Comment by markocikos** [comment]
> Hey @markocikos `@include media-breakpoint-down(sm)` for Bootstrap is `@media (max-width: 767.98px) { ... }` that's why I suggested to change it into `@include media-breakpoint-up(md)` that is `@media (min-width: 768px) { ... }` https://getbootstrap.com/docs/4.3/layout/overview/#responsive-breakpoint

@eduardoallegrini Yes, I understood this. That's why I'm saying I intentionally changed the solution in this PR, as 576px looks to me like a more fitting breakpoint. If you disagree, it's easy to revert to 768px.

**Pull request closed without merging**
