### PR TITLE
LPS-114084 Update test in segments-web

### PR DESCRIPTION
**Pull request by eduardoallegrini**
Trying tests one more time

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test:relevant

**Comment by eduardoallegrini** [comment]
Hey @john-co can you help me here? 😞

This is the 3rd time I try to run the tests
https://github.com/jbalsas/liferay-portal/pull/2214
https://github.com/eduardoallegrini/liferay-portal/pull/91

**Comment by john-co** [comment]
Quick review: I think the js-unit test failure looks related:

```
     [exec] > Task :apps:app-builder:app-builder-web:packageRunTest FAILED
     [exec] PASS test/js/components/list-view/ListView.es.js (6.269s)
     [exec] PASS test/js/components/permissions/PermissionsModal.es.js (7.595s)
     [exec] PASS test/js/pages/apps/DropDownWithSearch.es.js
     [exec] PASS test/js/pages/object/ViewObject.es.js (8.265s)
     [exec] FAIL test/js/pages/table-view/EditTableView.es.js (9.466s)
     [exec]   ??? Console
     [exec] 
     [exec]     console.error ../../../node_modules/react-dom/cjs/react-dom.development.js:530
     [exec]       Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?
     [exec]       
     [exec]       Check the render method of `_default`.
     [exec]           in ClayContentRow (created by _default)
     [exec]           in _default (created by FieldTypeWrapper)
     [exec]           in FieldTypeWrapper (created by _default)
     [exec]           in _default (created by FieldsTabContent)
     [exec]           in FieldsTabContent (created by SidebarTabs)
     [exec]           in div (created by SidebarTabContent)
     [exec]           in div (created by SidebarTabContent)
     [exec]           in SidebarTabContent (created by SidebarTabs)
     [exec]           in SidebarTabs (created by _default)
     [exec]           in div (created by SidebarBody)
     [exec]           in SidebarBody (created by _default)
     [exec]           in div (created by ForwardRef)
     [exec]           in div (created by ForwardRef)
     [exec]           in ForwardRef (created by _default)
     [exec]           in div (created by _default)
     [exec]           in _default
     [exec]           in Unknown (created by Wrapper)
     [exec]           in Wrapper
     [exec]           in div
     [exec]           in Unknown (created by Context.Consumer)
     [exec]           in withRouter() (created by _default)
     [exec]           in Unknown (created by Context.Consumer)
     [exec]           in withRouter() (created by _default)
     [exec]           in _default
     [exec]           in Unknown
     [exec]           in Router (created by HashRouter)
     [exec]           in HashRouter (created by _default)
     [exec]           in AppContextProvider (created by _default)
     [exec]           in _default
     [exec] 
     [exec]   ??? EditTableView ??? renders
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `EditTableView renders 1`
     [exec] 
     [exec]     - Snapshot  - 7
     [exec]     + Received  + 6
     [exec] 
     [exec]     @@ -93,11 +93,11 @@
     [exec]                 <div
     [exec]                   class="sidebar-header"
     [exec]                 >
     [exec]                   <form>
     [exec]                     <div
     [exec]     -                 class="autofit-row sidebar-section"
     [exec]     +                 class="sidebar-section autofit-row"
     [exec]                     >
     [exec]                       <div
     [exec]                         class="autofit-col autofit-col-expand"
     [exec]                       >
     [exec]                         <div
     [exec]     @@ -158,11 +158,11 @@
     [exec]                 >
     [exec]                   <nav
     [exec]                     class="component-tbar tbar"
     [exec]                   >
     [exec]                     <div
     [exec]     -                 class="container-fluid"
     [exec]     +                 class="container-fluid container-fluid-max-xl"
     [exec]                     >
     [exec]                       <ul
     [exec]                         class="nav nav-underline"
     [exec]                         role="tablist"
     [exec]                       >
     [exec]     @@ -197,16 +197,15 @@
     [exec]                     <div
     [exec]                       class="active fade mt-3 show tab-pane"
     [exec]                       role="tabpanel"
     [exec]                     >
     [exec]                       <div
     [exec]     -                   class="autofit-row autofit-row-center field-type"
     [exec]     +                   class="field-type autofit-row autofit-row-center"
     [exec]                         data-field-type-name="Text"
     [exec]     -                   draggable="true"
     [exec]                       >
     [exec]                         <div
     [exec]     -                     class="autofit-col pl-2 pr-2"
     [exec]     +                     class="pl-2 pr-2 autofit-col"
     [exec]                         >
     [exec]                           <svg
     [exec]                             class="lexicon-icon lexicon-icon-drag"
     [exec]                             role="presentation"
     [exec]                           >
     [exec]     @@ -214,11 +213,11 @@
     [exec]                               xlink:href="#drag"
     [exec]                             />
     [exec]                           </svg>
     [exec]                         </div>
     [exec]                         <div
     [exec]     -                     class="autofit-col pr-2"
     [exec]     +                     class="pr-2 autofit-col"
     [exec]                         >
     [exec]                           <span
     [exec]                             class="sticker data-layout-builder-field-sticker sticker-rounded sticker-light sticker-md"
     [exec]                           >
     [exec]                             <span
     [exec]     @@ -234,11 +233,11 @@
     [exec]                               </svg>
     [exec]                             </span>
     [exec]                           </span>
     [exec]                         </div>
     [exec]                         <div
     [exec]     -                     class="autofit-col autofit-col-expand pr-2"
     [exec]     +                     class="pr-2 autofit-col autofit-col-expand"
     [exec]                         >
     [exec]                           <h4
     [exec]                             class="list-group-title text-truncate"
     [exec]                           >
     [exec]                             <span>
     [exec] 
     [exec]       221 | 		});
     [exec]       222 | 
     [exec]     > 223 | 		expect(asFragment()).toMatchSnapshot();
     [exec]           | 		                     ^
     [exec]       224 | 	});
     [exec]       225 | 
     [exec]       226 | 	it('renders with two fields in the sidebar and saves successfully', async () => {
     [exec] 
     [exec]       at Object.toMatchSnapshot (test/js/pages/table-view/EditTableView.es.js:223:24)
     [exec] 
     [exec]  ??? 1 snapshot failed.
     [exec] PASS test/js/pages/table-view/ListTableViews.es.js
     [exec] PASS test/js/components/management-toolbar/ManagementToolbarFilterAndOrder.es.js
     [exec] PASS test/js/pages/native-object/ListNativeObjects.es.js (9.847s)
     [exec] PASS test/js/pages/apps/ListAppsTabs.es.js
     [exec] PASS test/js/components/translation-manager/TranslationManager.es.js
     [exec] PASS test/js/pages/apps/ListStandardApps.es.js (7.307s)
     [exec] PASS test/js/components/toggle-switch/ToggleSwitch.es.js
     [exec] PASS test/js/components/popover/Popover.es.js
     [exec] PASS test/js/components/table/DropDown.es.js
     [exec] PASS test/js/components/management-toolbar/ManagementToolbarResultsBar.es.js
     [exec] PASS test/js/pages/apps/ListApps.es.js
     [exec] PASS test/js/components/control-menu/ControlMenu.es.js
     [exec] PASS test/js/components/multi-step-nav/MultiStepNav.es.js
     [exec] PASS test/js/utils/toast.es.js
     [exec] PASS test/js/components/management-toolbar/ManagementToolbar.es.js
     [exec] PASS test/js/utils/utils.es.js
     [exec] PASS test/js/pages/custom-object/ListCustomObjects.es.js (11.18s)
     [exec] PASS test/js/components/table/EmptyState.es.js
     [exec] PASS test/js/components/upper-toolbar/UpperToolbar.es.js
     [exec] PASS test/js/components/popover/PopoverBase.es.js
     [exec] 
     [exec] Summary of all failing tests
     [exec] FAIL test/js/pages/table-view/EditTableView.es.js (9.466s)
     [exec]   ??? EditTableView ??? renders
     [exec] 
     [exec]     expect(received).toMatchSnapshot()
     [exec] 
     [exec]     Snapshot name: `EditTableView renders 1`
     [exec] 
     [exec]     - Snapshot  - 7
     [exec]     + Received  + 6
     [exec] 
     [exec]     @@ -93,11 +93,11 @@
     [exec]                 <div
     [exec]                   class="sidebar-header"
     [exec]                 >
     [exec]                   <form>
     [exec]                     <div
     [exec]     -                 class="autofit-row sidebar-section"
     [exec]     +                 class="sidebar-section autofit-row"
     [exec]                     >
     [exec]                       <div
     [exec]                         class="autofit-col autofit-col-expand"
     [exec]                       >
     [exec]                         <div
     [exec]     @@ -158,11 +158,11 @@
     [exec]                 >
     [exec]                   <nav
     [exec]                     class="component-tbar tbar"
     [exec]                   >
     [exec]                     <div
     [exec]     -                 class="container-fluid"
     [exec]     +                 class="container-fluid container-fluid-max-xl"
     [exec]                     >
     [exec]                       <ul
     [exec]                         class="nav nav-underline"
     [exec]                         role="tablist"
     [exec]                       >
     [exec]     @@ -197,16 +197,15 @@
     [exec]                     <div
     [exec]                       class="active fade mt-3 show tab-pane"
     [exec]                       role="tabpanel"
     [exec]                     >
     [exec]                       <div
     [exec]     -                   class="autofit-row autofit-row-center field-type"
     [exec]     +                   class="field-type autofit-row autofit-row-center"
     [exec]                         data-field-type-name="Text"
     [exec]     -                   draggable="true"
     [exec]                       >
     [exec]                         <div
     [exec]     -                     class="autofit-col pl-2 pr-2"
     [exec]     +                     class="pl-2 pr-2 autofit-col"
     [exec]                         >
     [exec]                           <svg
     [exec]                             class="lexicon-icon lexicon-icon-drag"
     [exec]                             role="presentation"
     [exec]                           >
     [exec]     @@ -214,11 +213,11 @@
     [exec]                               xlink:href="#drag"
     [exec]                             />
     [exec]                           </svg>
     [exec]                         </div>
     [exec]                         <div
     [exec]     -                     class="autofit-col pr-2"
     [exec]     +                     class="pr-2 autofit-col"
     [exec]                         >
     [exec]                           <span
     [exec]                             class="sticker data-layout-builder-field-sticker sticker-rounded sticker-light sticker-md"
     [exec]                           >
     [exec]                             <span
     [exec]     @@ -234,11 +233,11 @@
     [exec]                               </svg>
     [exec]                             </span>
     [exec]                           </span>
     [exec]                         </div>
     [exec]                         <div
     [exec]     -                     class="autofit-col autofit-col-expand pr-2"
     [exec]     +                     class="pr-2 autofit-col autofit-col-expand"
     [exec]                         >
     [exec]                           <h4
     [exec]                             class="list-group-title text-truncate"
     [exec]                           >
     [exec]                             <span>
     [exec] 
     [exec]       221 | 		});
     [exec]       222 | 
     [exec]     > 223 | 		expect(asFragment()).toMatchSnapshot();
     [exec]           | 		                     ^
     [exec]       224 | 	});
     [exec]       225 | 
     [exec]       226 | 	it('renders with two fields in the sidebar and saves successfully', async () => {
     [exec] 
     [exec]       at Object.toMatchSnapshot (test/js/pages/table-view/EditTableView.es.js:223:24)
     [exec] 
     [exec] 
     [exec] Snapshot Summary
     [exec]  ??? 1 snapshot failed from 1 test suite. Inspect your code changes or re-run jest with `-u` to update them.
     [exec] 
     [exec] Test Suites: 1 failed, 25 passed, 26 total
     [exec] Tests:       1 failed, 100 passed, 101 total
     [exec] Snapshots:   1 failed, 6 passed, 7 total
     [exec] Time:        16.647s, estimated 33s
     [exec] Ran all test suites.
     [exec] Command /opt/dev/projects/github/liferay-portal/modules/node_modules/liferay-npm-scripts/node_modules/.bin/jest --config TEMP_jest.config.json exited with code 1
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by john-co** [comment]
The other workflow/kaleo tests are unrelated. I've seen them in another PR, https://github.com/liferay-frontend/liferay-portal/pull/7#issuecomment-644980441 should quarantine the kaleo test, can cherry pick if needed. And I believe the workflow one should be fixed in upstream by https://github.com/liferay-frontend/liferay-portal/pull/7#issuecomment-644973522

**Comment by wincent** [comment]
At first glance, those snapshot tests look like they can just be updated (`yarn test -u`). To my eye, the same classes are there, just the order has changed.

**Comment by wincent** [comment]
Except for the `draggable="true"` change...

**Comment by eduardoallegrini** [comment]
Decided to split in 2:
- Part A https://github.com/liferay-frontend/liferay-portal/pull/28
- Part B https://github.com/liferay-frontend/liferay-portal/pull/30

**Pull request closed without merging**
