### PR TITLE
LPS-108500 delete no necessary sticker-static class

### PR DESCRIPTION
**Pull request by boton**

### CODE REVIEW

**Comment by boton** [comment]
Reviewed here: wincent#173

/cc @AliciaGarciaGarcia

**Comment by eduardoallegrini** [comment]
The `sticker-static` class was removed long time ago
https://github.com/liferay/clay/commit/03636889b9f7783ae1909061dcfdb994cc23fc22

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/86221.

**Pull request closed without merging**
