### PR TITLE
LPS-53664

### PR DESCRIPTION
**Pull request by p2kmgcl**
/cc @marcoscv-work

### CODE REVIEW

**Comment by p2kmgcl** [comment]
@eduardoallegrini sin prisa :rainbow:

**Comment by p2kmgcl** [comment]
I found that the "portlet-dropzone" class is being added on an ftl template in portal-web. I think there is no other module where I can put this css :S
https://github.com/liferay/liferay-portal/blob/master/portal-web/docroot/html/common/themes/bottom_js.jspf#L131

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
Pull request submitted to https://github.com/brianchandotcom/liferay-portal/pull/84945. [See changes here.](https://github.com/eduardoallegrini/liferay-portal/compare/abd6f26e64b3~1...abd6f26e64b3)

**Pull request closed without merging**
