### PR TITLE
LPS-112626 Upgrade aui:container into clay:container

### PR DESCRIPTION
**Pull request by jbalsas**

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
Just started reviewing :)

**Comment by eduardoallegrini** [comment]
Hey @jbalsas can you check if the files are still compiling? I tried to run `gradlew clean deploy -a` but I got the following error:
> file:/Users/eduardoallegrini/projects/liferay-portal/liferay-portal/modules/apps/roles/roles-admin-web/classes/META-INF/resources/edit_role_permissions.jsp(68,0) PWC6142: No tag "container" defined in tag library imported with prefix "clay" (it worked in the previous pr)

**Comment by jbalsas** [comment]
I’ll check again tomorrow, Edu, just follow from your previous PR if this one gives you trouble :(

**Comment by jbalsas** [comment]
Hey @eduardoallegrini, I've push-forced the changes here. See comment at https://github.com/marcoscv-work/liferay-portal/pull/316. I tested and the edit_roles view seems to work for me. I amended your initial commit to use `className` instead of `cssClass` and also added an additional one namespacing the `id` attribute which was done by default initially and we no longer do.

**Comment by eduardoallegrini** [comment]
Pull request submitted to https://github.com/jbalsas/liferay-portal/pull/2160. [See changes here.](https://github.com/eduardoallegrini/liferay-portal/compare/6acfcdc71d52~1...6acfcdc71d52)

**Pull request closed without merging**
