### PR TITLE
LPS-104700 Reactivate the compat-dropdowns layer in the classic and admin themes

### PR DESCRIPTION
**Pull request by eduardoallegrini**

### CODE REVIEW

**Comment by eduardoallegrini** [comment]
ci:test

**Comment by john-co** [comment]
Just started reviewing :)

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark:

**Comment by john-co** [comment]
**Comparison:**
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=3&testrayRunIdB=884950104&testrayRunIdA=885329780&statusB=2

Test failures in comparison and the uniques in the `ci test default` results github comment look like flukes or flaky.

**Comment by marcoscv-work** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Pull request closed without merging**
