### PR TITLE
LPS 165784

### PR DESCRIPTION
**Pull request by edalgrin**
- LPS-165784 Replace remote-apps with client-extensions category label
- LPS-165784 Generate language files

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:bundle

**Comment by john-co** [comment]
ci:test:bundle

**Comment by john-co** [comment]
ci:test:frontend-remote-apps

**Comment by edalgrin** [comment]
Thanks @mateusralv @john-co for looking into this, let me know if I can help or should I move the PR to the team repo!

**Comment by mateusralv** [comment]
@edalgrin Thanks for the update. I'll take a look.

**Comment by john-co** [comment]
ci:test:frontend-remote-apps

**Comment by john-co** [comment]
ci:test:frontend-remote-apps

**Comment by john-co** [comment]
Reviewed. Test failures are unrelated. :heavy_check_mark: 

Ok to manually forward from QA perspective. Pending dev approval.

**Comment by john-co** [comment]
Hi @edalgrin , I pushed in the poshi test commits related to this story.

**Comment by john-co** [comment]
@edalgrin, is this ready for dev review? Would you like us to forward to liferay-frontend?

**Comment by edalgrin** [comment]
Yeah it's ready, I'll do it today! Thank you

**Comment by edalgrin** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/127523

**Pull request closed without merging**
